In [1]:
import pandas as pd
import json
from keras.preprocessing.text import text_to_word_sequence
import random
import re

Using TensorFlow backend.
C:\Users\Naveeta\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Naveeta\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Naveeta\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Naveeta\Anaconda3\lib\site-packages\tensorflow\python\framework\d

In [2]:
with open('SVAMP.json', 'r') as data_file:
    json_data = data_file.read()

In [3]:
train_df = pd.read_json(json_data, orient='records')

In [4]:
train_df.head(5)

ID                                               Body  \
0  chal-1  Each pack of dvds costs 76 dollars. If there i...   
1  chal-2  Dan had $ 3 left with him after he bought a ca...   
2  chal-3  Paco had 26 salty cookies and 17 sweet cookies...   
3  chal-4  43 children were riding on the bus. At the bus...   
4  chal-5  28 children were riding on the bus. At the bus...   

                                            Question         Equation  Answer  \
0      How much do you have to pay to buy each pack?  ( 76.0 - 25.0 )      51   
1                   How much did the candy bar cost?    ( 4.0 - 3.0 )       1   
2         How many salty cookies did Paco have left?   ( 26.0 - 9.0 )      17   
3  How many children got off the bus at the bus s...  ( 43.0 - 21.0 )      22   
4  How many more children got on the bus than tho...  ( 30.0 - 28.0 )       2   

          Type  
0  Subtraction  
1  Subtraction  
2  Subtraction  
3  Subtraction  
4  Subtraction

In [5]:
train_df.shape

(1000, 6)

In [6]:
lines = list(train_df.Body)
lines2 = list(train_df.Equation)

In [8]:
pairs = list(zip(lines, lines2))
random.shuffle(pairs)

In [14]:
import numpy as np
input_docs = []
target_docs = []
input_tokens = set()
target_tokens = set()
for line in pairs:
    input_doc, target_doc = line[0], line[1]
  # Appending each input sentence to input_docs
    input_docs.append(input_doc)
  # Splitting words from punctuation  
    target_doc = " ".join(re.findall(r"[\w']+|[^\s\w]", target_doc))
  # Redefine target_doc below and append it to target_docs
    target_doc = '<START> ' + target_doc + ' <END>'
    target_docs.append(target_doc)
  # Now we split up each sentence into words and add each unique word to our vocabulary set
    for token in re.findall(r"[\w']+|[^\s\w]", input_doc):
        if token not in input_tokens:
            input_tokens.add(token)
    for token in target_doc.split():
        if token not in target_tokens:
            target_tokens.add(token)
input_tokens = sorted(list(input_tokens))
target_tokens = sorted(list(target_tokens))
num_encoder_tokens = len(input_tokens)
num_decoder_tokens = len(target_tokens)

In [16]:
input_features_dict = dict(
    [(token, i) for i, token in enumerate(input_tokens)])
target_features_dict = dict(
    [(token, i) for i, token in enumerate(target_tokens)])
reverse_input_features_dict = dict(
    (i, token) for token, i in input_features_dict.items())
reverse_target_features_dict = dict(
    (i, token) for token, i in target_features_dict.items())

In [17]:
#Maximum length of sentences in input and target documents
max_encoder_seq_length = max([len(re.findall(r"[\w']+|[^\s\w]", input_doc)) for input_doc in input_docs])
max_decoder_seq_length = max([len(re.findall(r"[\w']+|[^\s\w]", target_doc)) for target_doc in target_docs])
encoder_input_data = np.zeros(
(len(input_docs), max_encoder_seq_length, num_encoder_tokens), dtype='float32')
decoder_input_data = np.zeros(
(len(input_docs), max_decoder_seq_length, num_decoder_tokens),
dtype='float32')
decoder_target_data = np.zeros(
(len(input_docs), max_decoder_seq_length, num_decoder_tokens), dtype='float32')
for line, (input_doc, target_doc) in enumerate(zip(input_docs, target_docs)):
    for timestep, token in enumerate(re.findall(r"[\w']+|[^\s\w]", input_doc)):
    #Assign 1. for the current line, timestep, & word in encoder_input_data
        encoder_input_data[line, timestep, input_features_dict[token]] = 1.
    for timestep, token in enumerate(target_doc.split()):
        decoder_input_data[line, timestep, target_features_dict[token]] = 1.
        if timestep > 0:
            decoder_target_data[line, timestep - 1, target_features_dict[token]] = 1.

In [18]:
from tensorflow import keras
from keras.layers import Input, LSTM, Dense
from keras.models import Model
#Dimensionality
dimensionality = 256
#The batch size and number of epochs
batch_size = 256
epochs = 100
#Encoder
encoder_inputs = Input(shape=(None, num_encoder_tokens))
encoder_lstm = LSTM(dimensionality, return_state=True)
encoder_outputs, state_hidden, state_cell = encoder_lstm(encoder_inputs)
encoder_states = [state_hidden, state_cell]#Decoder
decoder_inputs = Input(shape=(None, num_decoder_tokens))
decoder_lstm = LSTM(dimensionality, return_sequences=True, return_state=True)
decoder_outputs, decoder_state_hidden, decoder_state_cell = decoder_lstm(decoder_inputs, initial_state=encoder_states)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

Instructions for updating:
Colocations handled automatically by placer.


In [19]:
#Model
training_model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
#Compiling
training_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'], sample_weight_mode='temporal')
#Training
training_model.fit([encoder_input_data, decoder_input_data], decoder_target_data, batch_size = batch_size, epochs = epochs, validation_split = 0.2)

Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Train on 800 samples, validate on 200 samples
Epoch 1/100
800/800 [==============================] - 18s 23ms/step - loss: 3.1820 - accuracy: 0.0722 - val_loss: 3.1560 - val_accuracy: 0.2107
Epoch 2/100
800/800 [==============================] - 14s 17ms/step - loss: 3.0811 - accuracy: 0.1890 - val_loss: 2.3109 - val_accuracy: 0.1543
Epoch 3/100
800/800 [==============================] - 14s 17ms/step - loss: 2.0226 - accuracy: 0.1539 - val_loss: 1.6390 - val_accuracy: 0.1698
Epoch 4/100
800/800 [==============================] - 14s 18ms/step - loss: 1.5632 - accuracy: 0.1696 - val_loss: 1.4156 - val_accuracy: 0.2460
Epoch 5/100
800/800 [==============================] - 17s 21ms/step - loss: 1.3834 - accuracy: 0.2090 - val_loss: 1.3410 - val_accuracy: 0.2481
Epoch 6/100
800/800 [==============================] - 15s 19ms/step - loss: 1.3371 - accuracy: 0.2426 

800/800 [==============================] - 16s 20ms/step - loss: 0.7303 - accuracy: 0.3801 - val_loss: 0.7753 - val_accuracy: 0.3876
Epoch 54/100
800/800 [==============================] - 16s 20ms/step - loss: 0.7024 - accuracy: 0.3960 - val_loss: 0.7443 - val_accuracy: 0.3986
Epoch 55/100
800/800 [==============================] - 14s 18ms/step - loss: 0.6764 - accuracy: 0.4000 - val_loss: 0.7279 - val_accuracy: 0.3938
Epoch 56/100
800/800 [==============================] - 17s 21ms/step - loss: 0.6573 - accuracy: 0.4016 - val_loss: 0.7184 - val_accuracy: 0.3938
Epoch 57/100
800/800 [==============================] - 15s 18ms/step - loss: 0.6475 - accuracy: 0.4016 - val_loss: 0.7145 - val_accuracy: 0.3950
Epoch 58/100
800/800 [==============================] - 16s 20ms/step - loss: 0.6424 - accuracy: 0.4013 - val_loss: 0.7132 - val_accuracy: 0.3917
Epoch 59/100
800/800 [==============================] - 16s 21ms/step - loss: 0.6379 - accuracy: 0.4017 - val_loss: 0.7096 - val_accuracy

In [20]:
training_model.save('training_model.h5')

In [21]:
from keras.models import load_model
training_model = load_model('training_model.h5')
encoder_inputs = training_model.input[0]
encoder_outputs, state_h_enc, state_c_enc = training_model.layers[2].output
encoder_states = [state_h_enc, state_c_enc]
encoder_model = Model(encoder_inputs, encoder_states)

In [22]:
latent_dim = 256
decoder_state_input_hidden = Input(shape=(latent_dim,))
decoder_state_input_cell = Input(shape=(latent_dim,))
decoder_states_inputs = [decoder_state_input_hidden, decoder_state_input_cell]

In [23]:
decoder_outputs, state_hidden, state_cell = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_hidden, state_cell]
decoder_outputs = decoder_dense(decoder_outputs)

In [24]:
decoder_model = Model([decoder_inputs] + decoder_states_inputs, [decoder_outputs] + decoder_states)

In [25]:
def decode_response(test_input):
    #Getting the output states to pass into the decoder
    states_value = encoder_model.predict(test_input)
    #Generating empty target sequence of length 1
    target_seq = np.zeros((1, 1, num_decoder_tokens))
    #Setting the first token of target sequence with the start token
    target_seq[0, 0, target_features_dict['<START>']] = 1.
    
    #A variable to store our response word by word
    decoded_sentence = ''
    
    stop_condition = False
    while not stop_condition:
      #Predicting output tokens with probabilities and states
        output_tokens, hidden_state, cell_state = decoder_model.predict([target_seq] + states_value)
      #Choosing the one with highest probability
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_token = reverse_target_features_dict[sampled_token_index]
        decoded_sentence += " " + sampled_token#Stop if hit max length or found the stop token
        if (sampled_token == '<END>' or len(decoded_sentence) > max_decoder_seq_length):
            stop_condition = True
      #Update the target sequence
        target_seq = np.zeros((1, 1, num_decoder_tokens))
        target_seq[0, 0, sampled_token_index] = 1.
      #Update states
        states_value = [hidden_state, cell_state]
    return decoded_sentence

In [26]:
class Translator:
    exit_commands = ("quit", "pause", "exit", "goodbye", "bye", "later", "stop")
  
  #Method to start the translator
    def start(self):
        user_response = input("Give in an English sentence. :) \n")
        self.translate(user_response)
        
  
  #Method to handle the conversation
    def translate(self, reply):
        while not self.make_exit(reply):
            reply = input(self.generate_response(reply)+"\n")
#Method to convert user input into a matrix
    def string_to_matrix(self, user_input):
        tokens = re.findall(r"[\w']+|[^\s\w]", user_input)
        user_input_matrix = np.zeros((1, max_encoder_seq_length, num_encoder_tokens),dtype='float32')
        for timestep, token in enumerate(tokens):
            if token in input_features_dict:
                user_input_matrix[0, timestep, input_features_dict[token]] = 1.
        print(user_input_matrix)
        return user_input_matrix
  
  #Method that will create a response using seq2seq model we built
    def generate_response(self, user_input):
        input_matrix = self.string_to_matrix(user_input)
        chatbot_response = decode_response(input_matrix)
        #Remove <START> and <END> tokens from chatbot_response
        chatbot_response = chatbot_response.replace("<START>",'')
        chatbot_response = chatbot_response.replace("<END>",'')
        return chatbot_response
  
  #Method to check for exit commands
    def make_exit(self, reply):
        for exit_command in self.exit_commands:
            if exit_command in reply:
                print("Ok, have a great day!")
                return True
        return False
  
translator = Translator()

In [28]:
translator.start()

Give in an English sentence. :) 
Bryan took a look at his books as well . If Bryan has 0 books in each of his 1 bookshelves , how many books does he have in total ?
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
 ( ( . . 0 + 2 . 0 ) -
quit
Ok, have a great day!
